# Generated by Django 4.2.4 on 2023-08-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_subscribed',
            new_name='is_member',
        ),
    ]
