# Generated by Django 4.2.4 on 2023-08-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
