# Generated by Django 4.2.4 on 2023-08-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='featured',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=None),
        ),
    ]
